# name: Github Profile Contrib

# on:
#   schedule:
#     - cron: "0 0 * * 1-5"
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     name: generate-github-profile-contrib
#     steps:
#       - uses: actions/checkout@v2
#       - uses: yoshi389111/github-profile-3d-contrib@0.6.0
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           USERNAME: ${{ github.repository_owner }}
#       - name: Commit & Push
#         run: |
#           git config user.name JulioManoel
#           git config user.email juliobonow@gmail.com
#           git add -A .
#           git commit -m "Generated Profile Contrib"
#           git push
